title MaxCount Scavenge-On-Write

actor User
boundary "Stream Store Lib" as Lib
database "MS Sql DB" as DB

autonumber
User -> Lib : AppendToStream
Lib -> DB : AppendToStream
Lib -> DB : GetStreamMetadata
note right
        +1 network operation
end note
Lib -> Lib : if (metadata == null\n    || !metadata.MaxCount.HasValue)
Lib -> User : return
Lib -> DB : else GetStreamCount
note right
        +1 network operation
end note
Lib -> DB : foreach extranous item { delete item }
note right
        +0-2N network operations
        (each delete requires an append to $deleted)
end note
Lib -> User : return
