DROP PROCEDURE IF EXISTS append_to_stream_expected_version;
DROP PROCEDURE IF EXISTS append_to_stream_expected_version_any;
DROP PROCEDURE IF EXISTS append_to_stream_expected_version_empty_stream;
DROP PROCEDURE IF EXISTS append_to_stream_expected_version_no_stream;
DROP PROCEDURE IF EXISTS create_empty_stream;
DROP PROCEDURE IF EXISTS delete_stream;
DROP PROCEDURE IF EXISTS delete_stream_message;
DROP PROCEDURE IF EXISTS get_stream_metadata;
DROP PROCEDURE IF EXISTS list_streams;
DROP PROCEDURE IF EXISTS list_streams_starting_with;
DROP PROCEDURE IF EXISTS list_streams_ending_with;
DROP PROCEDURE IF EXISTS `read`;
DROP PROCEDURE IF EXISTS read_all;
DROP PROCEDURE IF EXISTS read_properties;
DROP PROCEDURE IF EXISTS read_head_position;
DROP PROCEDURE IF EXISTS read_json_data;
DROP PROCEDURE IF EXISTS read_stream_version_of_message_id;
DROP PROCEDURE IF EXISTS scavenge;
DROP PROCEDURE IF EXISTS set_stream_metadata;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS streams CASCADE;
