DROP PROCEDURE IF EXISTS read_properties;

CREATE PROCEDURE read_properties()
BEGIN

  SELECT INFORMATION_SCHEMA.TABLES.TABLE_COMMENT
  FROM INFORMATION_SCHEMA.TABLES
  WHERE INFORMATION_SCHEMA.TABLES.TABLE_SCHEMA = DATABASE()
    AND INFORMATION_SCHEMA.TABLES.TABLE_NAME = 'streams'
  LIMIT 1;

END;