name: PR

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Test
      run: bash build.sh
      shell: bash
